SHOW DATABASES;
CREATE DATABASE PaymentAppCLI;

USE PaymentAppCLI;

CREATE TABLE User(
Id INT PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
PhoneNumber  BIGINT UNIQUE NOT NULL,
DateOfBirth VARCHAR(20) NOT NULL,
Address VARCHAR(150) NOT NULL
);

SELECT * FROM User;

CREATE TABLE BankAccount(
Id INT PRIMARY KEY,
AccountNumber INT UNIQUE NOT NULL,
AcctIFSC VARCHAR(20) NOT NULL,
BankName VARCHAR(30) NOT NULL,
AcctType VARCHAR(20) NOT NULL,
UserId  INT NOT NULL, FOREIGN KEY(UserId) REFERENCES User(Id)
);

SELECT * FROM BankAccount;

CREATE TABLE Transaction(
Id int PRIMARY KEY,
DateTime VARCHAR(20) NOT NULL,
Amount FLOAT NOT NULL,
txnSource VARCHAR(20) NOT NULL,
txnDestination VARCHAR(20) NOT NULL,
UserId  INT NOT NULL, FOREIGN KEY(UserId) REFERENCES User(Id)
);

SELECT * FROM Transaction;
